### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by Saransh-cpp** [TomTranter/pybamm_pnm#11]
I was going through the repository and I found that the examples available as jupyter notebooks error out -

1. [`current-density-distribution.ipynb`](https://github.com/TomTranter/pybamm_pnm/blob/master/notebooks/current_density_distributions.ipynb) - The files `var_Current_collector_current_density_lower.mat`, `var_Current_collector_current_density_upper.mat`, and `MJ141-mid-top_m_cc_new.pnm` are missing. 2 of these files are available in the tests folder but there isn't any `8A` subdirectory present there.
2. [`solution-data-and-processed-variables.ipynb`](https://github.com/TomTranter/pybamm_pnm/blob/master/notebooks/solution-data-and-processed-variables.ipynb) - Is this notebook supposed to be the same as the one in PyBaMM? There were a few PyBaMM errors in this notebook like the variable name `'Negative particle surface concentration'` is without units.
3. The third notebook doesn't open as the `JSON` is invalid. I tried fixing the `JSON` but then it started giving another error. 

And I also wanted to ask if the scripts in the [run_scripts](https://github.com/TomTranter/pybamm_pnm/tree/master/run_scripts) folder are example scripts? I am also facing some issues with them but I don't know if they are supposed to run independently.

**Comment by TomTranter** [comment]
I am going to move examples into docs PR
