### ISSUE TITLE
Hello Stargazers

### ISSUE THREAD

**Issue by TomTranter** [TomTranter/pybamm_pnm#25]
Hi @helgestein and @mklanac,
I noticed you both starred this repo so have some interest in it. I guess you read one of my papers or noticed it used PyBaMM. I'm in the middle of a big refactor so thought I'd get in touch in case you would like to get more involved in the development. There are plenty of things to do and just having some extra QA on hand would be useful. I intend to tidy it all up and transfer it to the pybamm-team organisation and then publish a paper on the code in JOSS like I have recently done for liionpack https://joss.theoj.org/papers/10.21105/joss.04051
Any help would mean we could co-author the paper.
Thanks

**Comment by helgestein** [comment]
Hey Tom,

sounds great though I currently have zero free resources unfortunately but I might point one of my colleagues to this who is doing most of the parametrization now. Happy to beta test tough :)
Keep up the great work and cheers,
Helge
