### ISSUE TITLE
About ecm package

### ISSUE THREAD

**Issue by Jadhav-Sourabh** [TomTranter/pybamm_pnm#31]
@TomTranter @rtimms 

"ecm" package is depend on the python in between 2.5 to 2.9. 
and remaining packages will depend on python above 3.0

How can I use this?
because of the "ecm" package, I am not able to do any simulation.

please help me.

**Comment by Jadhav-Sourabh** [comment]
Can you please help to simulate jelly roll thermal model?
Help me with installing ecm package

**Comment by TomTranter** [comment]
Oh I see, that's an existing package. yeah it's also what I have called this one. In the process of renaming it JellyBaMM or something. I can help but not immediately. Like I said, it's still being reworked

**Comment by TomTranter** [comment]
See here for how help on installation https://github.com/TomTranter/pybamm_pnm/blob/main/.github/workflows/test_on_push.yml

**Comment by Jadhav-Sourabh** [comment]
Can you please share some reference papers or books for this modeling?

________________________________

**Comment by TomTranter** [comment]
https://iopscience.iop.org/article/10.1149/1945-7111/aba44b/meta
https://iopscience.iop.org/article/10.1149/1945-7111/abd44f/meta

**Comment by Jadhav-Sourabh** [comment]
Sir,

I read the papers and I want to appreciate you.
You are doing a great job.


________________________________
